import 'package:feeel/db/bundled_exercises.dart';

class DBMigrationMaps {
  static final pre300ToCurrentExercises = {
    1: BundledExercises.jumpingJacks,
    2: BundledExercises.wallSit,
    3: BundledExercises.pushUps,
    4: BundledExercises.abCrunches,
    5: BundledExercises.stepUps,
    6: BundledExercises.squats,
    7: BundledExercises.chairDips,
    8: BundledExercises.forearmPlank,
    9: BundledExercises.highKnees,
    10: BundledExercises.lunges,
    11: BundledExercises.pushUpRotations,
    12: BundledExercises.sidePlankL,
    13: BundledExercises.sidePlankR,
    14: BundledExercises.sideSplitSquatsL,
    15: BundledExercises.bulgarianSplitSquatsL,
    16: BundledExercises.bulgarianSplitSquatsR,
    17: BundledExercises.pistolSquatsL,
    18: BundledExercises.pistolSquatsR,
    19: BundledExercises.kneelingKickbacks,
    20: BundledExercises.calfRaisesL,
    21: BundledExercises.calfRaisesR,
    22: BundledExercises.sideSplitSquatsR,
    23: BundledExercises.splitSquatsL,
    24: BundledExercises.splitSquatsR,
    25: BundledExercises.jumpRopeBasic,
    26: BundledExercises.armCirclesFW,
    27: BundledExercises.pikePushUps,
    28: BundledExercises.mountainClimbers,
    29: BundledExercises.fourCountBurpees,
    30: BundledExercises.noPushUpBurpees,
    31: BundledExercises.squatThrusts,
    32: BundledExercises.reverseLunges,
    33: BundledExercises.legRaises,
    34: BundledExercises.floorDips,
    35: BundledExercises.highPlank,
    36: BundledExercises.armCirclesBW,
    37: BundledExercises.childsPose,
    38: BundledExercises.pullUp,
    39: BundledExercises.kettlebellDeadlift,
    40: BundledExercises.sumoSquat,
    41: BundledExercises.shoulderRotationFW,
    42: BundledExercises.shoulderRotationBW,
    43: BundledExercises.shoulderShrug,
    44: BundledExercises.chinTuck,
    45: BundledExercises.headTurns,
    46: BundledExercises.backNeckStretch,
    47: BundledExercises.lateralNeckStretchL,
    48: BundledExercises.lateralNeckStretchR,
    49: BundledExercises.frontNeckStretch,
    50: BundledExercises.alternatingBicepCurls,
    51: BundledExercises.levatorScapulaeStretchL,
    52: BundledExercises.levatorScapulaeStretchR,
    53: BundledExercises.neckCirclesCW,
    54: BundledExercises.neckCirclesCCW,
    55: BundledExercises.neckHalfCircles,
    56: BundledExercises.headTilts
  };

  // static final currentToPre300Exercises = {
//     DefaultExercises.jumpingJacks: 1,
//     DefaultExercises.wallSit: 2,
//     DefaultExercises.pushUps: 3,
//     DefaultExercises.abCrunches: 4,
//     DefaultExercises.stepUps: 5,
//     DefaultExercises.squats: 6,
//     DefaultExercises.chairDips: 7,
//     DefaultExercises.forearmPlank: 8,
//     DefaultExercises.highKnees: 9,
//     DefaultExercises.lunges: 10,
//     DefaultExercises.pushUpRotations: 11,
//     DefaultExercises.sidePlankL: 12,
//     DefaultExercises.sidePlankR: 13,
//     DefaultExercises.sideSplitSquatsL: 14,
//     DefaultExercises.bulgarianSplitSquatsL: 15,
//     DefaultExercises.bulgarianSplitSquatsR: 16,
//     DefaultExercises.pistolSquatsL: 17,
//     DefaultExercises.pistolSquatsR: 18,
//     DefaultExercises.kneelingKickbacks: 19,
//     DefaultExercises.calfRaisesL: 20,
//     DefaultExercises.calfRaisesR: 21,
//     DefaultExercises.sideSplitSquatsR: 22,
//     DefaultExercises.splitSquatsL: 23,
//     DefaultExercises.splitSquatsR: 24,
//     DefaultExercises.jumpRopeBasic: 25,
//     DefaultExercises.armCirclesFW: 26,
//     DefaultExercises.pikePushUps: 27,
//     DefaultExercises.mountainClimbers: 28,
//     DefaultExercises.fourCountBurpees: 29,
//     DefaultExercises.noPushUpBurpees: 30,
//     DefaultExercises.squatThrusts: 31,
//     DefaultExercises.reverseLunges: 32,
//     DefaultExercises.legRaises: 33,
//     DefaultExercises.florrDips: 34, // v2.2.0
//     DefaultExercises.highPlank: 35,
//     DefaultExercises.armCirclesBW: 36,
//     DefaultExercises.childsPose: 37,
//     DefaultExercises.pullUp: 38,
//     DefaultExercises.kettlebellDeadlift: 39,
//     DefaultExercises.sumoSquat: 40,
//     DefaultExercises.shoulderRotationFW: 41,
//     DefaultExercises.shoulderRotationBW: 42,
//     DefaultExercises.shoulderShrug: 43,
//     DefaultExercises.chinTuck: 44,
//     DefaultExercises.headTurns: 45,
//     DefaultExercises.backNeckStretch: 46,
//     DefaultExercises.lateralNeckStretchL: 47,
//     DefaultExercises.lateralNeckStretchR: 48,
//     DefaultExercises.frontNeckStretch: 49,
//     DefaultExercises.alternatingBicepCurls: 50,
//     DefaultExercises.levatorScapulaeStretchL: 51,
//     DefaultExercises.levatorScapulaeStretchR: 52,
//     DefaultExercises.neckCirclesCW: 53,
//     DefaultExercises.neckCirclesCCW: 54,
//     DefaultExercises.neckHalfCircles: 55,
//     DefaultExercises.headTilts: 56
//   };
}
