import 'package:feeel/db/default_exercises.dart';

class DBMigrationMaps {
  static final pre300ToCurrentExercises = {
    1: DefaultExercises.jumpingJacks,
    2: DefaultExercises.wallSit,
    3: DefaultExercises.pushUps,
    4: DefaultExercises.abCrunches,
    5: DefaultExercises.stepUps,
    6: DefaultExercises.squats,
    7: DefaultExercises.chairDips,
    8: DefaultExercises.forearmPlank,
    9: DefaultExercises.highKnees,
    10: DefaultExercises.lunges,
    11: DefaultExercises.pushUpRotations,
    12: DefaultExercises.sidePlankL,
    13: DefaultExercises.sidePlankR,
    14: DefaultExercises.sideSplitSquatsL,
    15: DefaultExercises.bulgarianSplitSquatsL,
    16: DefaultExercises.bulgarianSplitSquatsR,
    17: DefaultExercises.pistolSquatsL,
    18: DefaultExercises.pistolSquatsR,
    19: DefaultExercises.kneelingKickbacks,
    20: DefaultExercises.calfRaisesL,
    21: DefaultExercises.calfRaisesR,
    22: DefaultExercises.sideSplitSquatsR,
    23: DefaultExercises.splitSquatsL,
    24: DefaultExercises.splitSquatsR,
    25: DefaultExercises.jumpRopeBasic,
    26: DefaultExercises.armCirclesFW,
    27: DefaultExercises.pikePushUps,
    28: DefaultExercises.mountainClimbers,
    29: DefaultExercises.fourCountBurpees,
    30: DefaultExercises.noPushUpBurpees,
    31: DefaultExercises.squatThrusts,
    32: DefaultExercises.reverseLunges,
    33: DefaultExercises.legRaises,
    34: DefaultExercises.florrDips,
    35: DefaultExercises.highPlank,
    36: DefaultExercises.armCirclesBW,
    37: DefaultExercises.childsPose,
    38: DefaultExercises.pullUp,
    39: DefaultExercises.kettlebellDeadlift,
    40: DefaultExercises.sumoSquat,
    41: DefaultExercises.shoulderRotationFW,
    42: DefaultExercises.shoulderRotationBW,
    43: DefaultExercises.shoulderShrug,
    44: DefaultExercises.chinTuck,
    45: DefaultExercises.headTurns,
    46: DefaultExercises.backNeckStretch,
    47: DefaultExercises.lateralNeckStretchL,
    48: DefaultExercises.lateralNeckStretchR,
    49: DefaultExercises.frontNeckStretch,
    50: DefaultExercises.alternatingBicepCurls,
    51: DefaultExercises.levatorScapulaeStretchL,
    52: DefaultExercises.levatorScapulaeStretchR,
    53: DefaultExercises.neckCirclesCW,
    54: DefaultExercises.neckCirclesCCW,
    55: DefaultExercises.neckHalfCircles,
    56: DefaultExercises.headTilts
  };

  // static final currentToPre300Exercises = {
//     DefaultExercises.jumpingJacks: 1,
//     DefaultExercises.wallSit: 2,
//     DefaultExercises.pushUps: 3,
//     DefaultExercises.abCrunches: 4,
//     DefaultExercises.stepUps: 5,
//     DefaultExercises.squats: 6,
//     DefaultExercises.chairDips: 7,
//     DefaultExercises.forearmPlank: 8,
//     DefaultExercises.highKnees: 9,
//     DefaultExercises.lunges: 10,
//     DefaultExercises.pushUpRotations: 11,
//     DefaultExercises.sidePlankL: 12,
//     DefaultExercises.sidePlankR: 13,
//     DefaultExercises.sideSplitSquatsL: 14,
//     DefaultExercises.bulgarianSplitSquatsL: 15,
//     DefaultExercises.bulgarianSplitSquatsR: 16,
//     DefaultExercises.pistolSquatsL: 17,
//     DefaultExercises.pistolSquatsR: 18,
//     DefaultExercises.kneelingKickbacks: 19,
//     DefaultExercises.calfRaisesL: 20,
//     DefaultExercises.calfRaisesR: 21,
//     DefaultExercises.sideSplitSquatsR: 22,
//     DefaultExercises.splitSquatsL: 23,
//     DefaultExercises.splitSquatsR: 24,
//     DefaultExercises.jumpRopeBasic: 25,
//     DefaultExercises.armCirclesFW: 26,
//     DefaultExercises.pikePushUps: 27,
//     DefaultExercises.mountainClimbers: 28,
//     DefaultExercises.fourCountBurpees: 29,
//     DefaultExercises.noPushUpBurpees: 30,
//     DefaultExercises.squatThrusts: 31,
//     DefaultExercises.reverseLunges: 32,
//     DefaultExercises.legRaises: 33,
//     DefaultExercises.florrDips: 34, // v2.2.0
//     DefaultExercises.highPlank: 35,
//     DefaultExercises.armCirclesBW: 36,
//     DefaultExercises.childsPose: 37,
//     DefaultExercises.pullUp: 38,
//     DefaultExercises.kettlebellDeadlift: 39,
//     DefaultExercises.sumoSquat: 40,
//     DefaultExercises.shoulderRotationFW: 41,
//     DefaultExercises.shoulderRotationBW: 42,
//     DefaultExercises.shoulderShrug: 43,
//     DefaultExercises.chinTuck: 44,
//     DefaultExercises.headTurns: 45,
//     DefaultExercises.backNeckStretch: 46,
//     DefaultExercises.lateralNeckStretchL: 47,
//     DefaultExercises.lateralNeckStretchR: 48,
//     DefaultExercises.frontNeckStretch: 49,
//     DefaultExercises.alternatingBicepCurls: 50,
//     DefaultExercises.levatorScapulaeStretchL: 51,
//     DefaultExercises.levatorScapulaeStretchR: 52,
//     DefaultExercises.neckCirclesCW: 53,
//     DefaultExercises.neckCirclesCCW: 54,
//     DefaultExercises.neckHalfCircles: 55,
//     DefaultExercises.headTilts: 56
//   };
}
