name: feeel
description: Feeel is an open-source Android app for doing simple at-home exercises.

version: 2.2.0+4015

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  flutter_tts: ^3.2.2
  wakelock: ^0.5.6
  sqflite: ^2.0.0
  sqflite_common_ffi: ^2.1.0
  path_provider: ^2.0.6
  i18n_extension: ^4.1.3
  flutter_mailer: ^2.0.0
  image_picker: ^0.8.4
  shared_preferences: ^2.0.8
  audioplayers: ^0.20.1
  flutter_local_notifications: ^9.0.2
  flutter_native_timezone: ^2.0.0
  url_launcher: ^6.0.12
  adaptive_theme: ^2.3.0
  package_info_plus: ^1.3.0
  auto_size_text: ^3.0.0

  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  
  # moor: ^4.4.0
  # sqlite3_flutter_libs: ^0.5.0
  # path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  # flutter_launcher_icons: ^0.9.2
  screenshots:
    git: git://github.com/felixgabler/screenshots.git

  # moor_generator: ^4.4.0
  # build_runner: ^2.0.5

flutter_icons:
  # image_path: "assets/icon_generic.png"
  image_path_ios: "assets/icon_ios.png"
  android: false
  macos: false
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - README.md
