name: feeel
description: A simple home workout/exercise app that respects your privacy

version: 2.4.1+4241

publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  
  http: ^0.13.5
  flutter_tts: ^3.6.3
  wakelock: ^0.6.2
  path_provider: ^2.0.13
  i18n_extension: ^8.0.0
  shared_preferences: ^2.0.18
  audioplayers: ^3.0.1
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^2.0.0
  timezone: ^0.9.1
  url_launcher: ^6.1.10
  package_info_plus: ^3.0.3
  auto_size_text: ^3.0.0
  flutter_markdown: ^0.6.14
  flutter_staggered_animations: ^1.1.1
  date_format: ^2.0.6
  xdg_directories: ^0.2.0
  flutter_speed_dial: ^6.2.0
  diacritic: ^0.1.3

  get_it: ^7.2.0 # TODO get rid of this after full riverpod migration

  flutter_riverpod: ^2.3.1

  table_calendar: ^3.0.9
  share_plus: ^6.3.1
  cross_file: ^0.3.3
  file_picker: ^5.2.5
  dynamic_color: ^1.6.2 # for Material You theming
  
  archive: ^3.3.0


  drift: ^2.5.0
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.2
  freezed_annotation: ^2.2.0

dependency_overrides:
  intl: 0.18.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  # integration_test:
  #   sdk: flutter
  # flutter_driver:
  #   sdk: flutter

  drift_dev: ^2.5.2
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  freezed: ^2.3.2 # does not generate JSON so far, add json_annotation dep. and json_serializable dev dep. if needed


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - README.md
