name: feeel
description: Feeel is an open-source Android app for doing simple at-home exercises.

version: 2.1.5+4014

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.3
  flutter_tts: ^3.1.0
  wakelock: ^0.5.2
  sqflite: ^2.0.0
  sqflite_common_ffi: ^2.0.0
  path_provider: ^2.0.2
  i18n_extension: ^4.0.3
  flutter_mailer: ^2.0.0
  image_picker: ^0.8.0
  shared_preferences: ^2.0.6
  audioplayers: ^0.18.3
  flutter_local_notifications: ^5.0.0
  flutter_native_timezone: ^2.0.0
  url_launcher: ^6.0.6
  adaptive_theme: ^2.2.0
  package_info: ^2.0.2

dependency_overrides:
  args: ^2.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon_android_legacy.png"
  image_path_ios: "assets/icon_ios.png"
  adaptive_icon_background: "assets/icon_adaptive_bg.png"
  adaptive_icon_foreground: "assets/icon_adaptive_fg.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - README.md
