name: feeel
description: Feeel is an open-source Android app for doing simple at-home exercises.

version: 1.990+9

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  http: ^0.12.0
  flutter_tts: ^0.8.7
  wakelock: ^0.1.3
  sqflite: ^1.2.1
  path_provider: ^1.6.5
  i18n_extension: ^1.3.3
  drag_list: ^1.0.7
  flutter_mailer: ^0.4.2
  image_picker: ^0.6.3
  shared_preferences: ^0.5.6+3
  audioplayers: ^0.14.0
  flutter_local_notifications: ^1.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon_android_legacy.png"
  image_path_ios: "assets/icon_ios.png"
  adaptive_icon_background: "assets/icon_adaptive_bg.png"
  adaptive_icon_foreground: "assets/icon_adaptive_fg.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
