name: feeel
description: Feeel is an open-source Android app for doing simple at-home exercises.

version: 2.2.0+4015

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.3
  flutter_tts: ^3.2.2
  wakelock: ^0.5.2
  sqflite: ^2.0.0
  sqflite_common_ffi: ^2.0.0
  path_provider: ^2.0.2
  i18n_extension: ^4.0.3
  flutter_mailer: ^2.0.0
  image_picker: ^0.8.2
  shared_preferences: ^2.0.6
  audioplayers: ^0.19.1
  flutter_local_notifications: ^8.0.0
  flutter_native_timezone: ^2.0.0
  url_launcher: ^6.0.9
  adaptive_theme: ^2.2.0
  package_info: ^2.0.2
  # auto_size_text: ^3.0.0-nullsafety.0
  
  # moor: ^4.4.0
  # sqlite3_flutter_libs: ^0.5.0
  # path: ^1.8.0

dev_dependencies:
  # flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  # moor_generator: ^4.4.0
  # build_runner: ^2.0.5

flutter_icons:
  android: false
  ios: true
  image_path_ios: "assets/icon_ios.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - README.md
