# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  lane :beta do
    gradle(
      task: 'assemble',
      build_type: 'Release',
      project_dir: 'android/'
    )
    upload_to_play_store(
      track: 'beta',
      apk_paths: [
        'build/app/outputs/apk/release/app-arm64-v8a-release.apk',
        'build/app/outputs/apk/release/app-x86_64-release.apk',
        'build/app/outputs/apk/release/app-armeabi-v7a-release.apk',
        'build/app/outputs/apk/release/app-x86-release.apk'
      ]
    )
  end

  lane :playtest do
    upload_to_play_store(
      track: 'beta',
      apk_paths: [
        'build/app/outputs/apk/release/app-arm64-v8a-release.apk',
        'build/app/outputs/apk/release/app-x86_64-release.apk',
        'build/app/outputs/apk/release/app-armeabi-v7a-release.apk',
        'build/app/outputs/apk/release/app-x86-release.apk'
      ]
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(
      task: 'assemble',
      build_type: 'Release',
      project_dir: 'android/'
    )
    upload_to_play_store(
      apk_paths: [
        'build/app/outputs/apk/release/app-arm64-v8a-release.apk',
        'build/app/outputs/apk/release/app-x86_64-release.apk',
        'build/app/outputs/apk/release/app-armeabi-v7a-release.apk',
        'build/app/outputs/apk/release/app-x86-release.apk'
      ]
    )
  end
end
